targets:
  $default:
    builders:
      model_factory_generator|builder:
        generate_for:
          include:
            - lib/data/models/**.dart

      model_factory_generator|resolver:
        generate_for:
          include:
            - lib/data/models/**.dart
