// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library global;

export 'error_model.dart';
export 'pagination_model.dart';
