// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library repositories;

export 'user_repository.dart';
export 'data_mapper.dart';
