// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library repositories;

export 'mapper/mapper.exports.dart';
export 'user_repository.dart';
