// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library money_plan;

export 'list_money_plan_model.dart';
export 'money_plan_model.dart';
