// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library pages;

export 'f_goals_page.dart';
export 'auth/auth.exports.dart';
export 'splash_page.dart';
export 'receive_page.dart';
export 'pay_page.dart';
export 'base/base.exports.dart';
export 'profile_page.dart';
