// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library locals;

export 'biometric_auth_datasource.dart';
export 'local_auth_datasource.dart';
