// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library history;

export 'list_history_model.dart';
export 'history_model.dart';
