// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library gen_export;

export 'data/data.exports.dart';
export 'flavor.dart';
export 'logic/logic.exports.dart';
export 'main.dart';
export 'presentation/presentation.exports.dart';
