// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library xetia_shop;

export 'ui/ui.exports.dart';
export 'core/core.exports.dart';
export 'flavor.dart';
export 'gen_export.dart';
export 'logic/logic.exports.dart';
export 'utils/utils.exports.dart';
export 'repositories/repositories.exports.dart';
export 'main.dart';
export 'service/service.exports.dart';
export 'data/data.exports.dart';
export 'routes/routes.exports.dart';
