// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library entities;

export 'base_entity.dart';
export 'history_entity.dart';
export 'money_manage_entity.dart';
export 'money_plan_entity.dart';
export 'school_entity.dart';
export 'transaction_entity.dart';
export 'user_entity.dart';
export 'wallet_entity.dart';
