// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library user;

export 'user_model.dart';
export 'list_user_model.dart';
