// This file is automatically generated by tools.
// To update all exports inside project
// run :
// flutter pub run bin/gen_export
library school;

export 'list_school_model.dart';
export 'school_model.dart';
