# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "apps fintch"
  gradle(
      task: 'assemble',
      build_type: 'Release'
  )
  lane :android_beta_app do
      firebase_app_distribution(
          app: "1:127226419613:android:3364a3da747deb997a7774",
          testers: "sniren2002@gmail.com, ",
          release_notes: "1.0.1",
          firebase_cli_path: "/usr/local/bin/firebase",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
